@startuml

' Initial node
start

' Actions
:Receive Order;

' Fork - parallel activities
fork
    :Fill Order; 

    ' Decision node
    if () then ([priority order])
        :Overnight Delivery;
    else ([else])
        :Regular Delivery;
    endif

fork again
    :Send Invoice;
    :Receive Payment;
end fork

' Join - merge parallel flows
:Close Order;

' Final node
stop

@endmul